/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookShop.Login;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author bolem
 */
public class SplashScreen extends javax.swing.JFrame {
    private Timer timer = null;
    private final ActionListener actionListener;
    
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        // Loads default components
        initComponents();
       
        // Beeps on start
        Toolkit.getDefaultToolkit().beep();
        
        // Sets progress bar and messages at every progress tick
        actionListener = (ActionEvent e) -> {
            prgBar_Progress.setValue(prgBar_Progress.getValue() + 2);
            if (prgBar_Progress.getValue() <= 10) {
                lbl_ProgressMessage.setText("Starting....");
            }
            if (prgBar_Progress.getValue() > 10 && prgBar_Progress.getValue() <= 20) {
                lbl_MiddleImage.setVisible(true);
                lbl_ProgressMessage.setText("Loading....");
            }
            if (prgBar_Progress.getValue() > 20 && prgBar_Progress.getValue() < 30) {
                lbl_ProgressMessage.setText("Loading Connection Drivers....");
            }
            if (prgBar_Progress.getValue() == 30) {
                lbl_ProgressMessage.setText("Loading Connection Drivers Complete");
            }
            if (prgBar_Progress.getValue() > 30 && prgBar_Progress.getValue() < 50) {
                lbl_ProgressMessage.setText("Loading Server...");
            }
            if (prgBar_Progress.getValue() == 50) {
                lbl_ProgressMessage.setText("Loading Server Complete");
            }
            if (prgBar_Progress.getValue() > 50  && prgBar_Progress.getValue() <= 54) {
                lbl_ProgressMessage.setText("Half Way There");
            }
            if (prgBar_Progress.getValue() > 54  && prgBar_Progress.getValue() < 64) {
                lbl_ProgressMessage.setText("Loading Frames....");
            }
            if (prgBar_Progress.getValue() == 64) {
                lbl_ProgressMessage.setText("Loading Frames Complete");
            }
            if (prgBar_Progress.getValue() > 64 && prgBar_Progress.getValue() < 80) {
                lbl_ProgressMessage.setText("Loading Components....");
            }
            if (prgBar_Progress.getValue() == 80) {
                lbl_ProgressMessage.setText("Loading Components Complete");
            }
            if (prgBar_Progress.getValue() > 80 && prgBar_Progress.getValue() <= 90) {
                lbl_ProgressMessage.setText("Hang on tight. We're very close");
            }
            if (prgBar_Progress.getValue() > 90 && prgBar_Progress.getValue() <= 94) {
                lbl_ProgressMessage.setText("Just one sec....");
            }
            if (prgBar_Progress.getValue() > 94 && prgBar_Progress.getValue() < 98) {
                lbl_ProgressMessage.setText("Calling User LogIn");
            }
            if (prgBar_Progress.getValue() == 98) {
                // Calls user login panel and closes itself
                new AppLogin(null).setVisible(true);
                lbl_ProgressMessage.setText("Loading Complete");
            }
            if (prgBar_Progress.getValue() == 100) {
                // Closes itself
                dispose();
            }
        };
                
        // Sets timer
        timer = new Timer(300, actionListener);
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Splash = new javax.swing.JPanel();
        lbl_EndingImage = new javax.swing.JLabel();
        lbl_ProgressMessage = new javax.swing.JLabel();
        prgBar_Progress = new javax.swing.JProgressBar();
        lbl_CompanyIcon = new javax.swing.JLabel();
        lbl_TradeMarkSymbol = new javax.swing.JLabel();
        lbl_CopyrightMention = new javax.swing.JLabel();
        lbl_MiddleImage = new javax.swing.JLabel();
        lbl_startingImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(336, 295));
        setSize(new java.awt.Dimension(500, 350));

        panel_Splash.setBackground(new java.awt.Color(255, 255, 255));
        panel_Splash.setLayout(null);

        lbl_EndingImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_EndingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/Pics/bluesky.jpg"))); // NOI18N
        panel_Splash.add(lbl_EndingImage);
        lbl_EndingImage.setBounds(0, 0, 338, 149);

        lbl_ProgressMessage.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_ProgressMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_Splash.add(lbl_ProgressMessage);
        lbl_ProgressMessage.setBounds(0, 152, 338, 30);
        panel_Splash.add(prgBar_Progress);
        prgBar_Progress.setBounds(0, 183, 338, 14);

        lbl_CompanyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/Pics/logo.png"))); // NOI18N
        panel_Splash.add(lbl_CompanyIcon);
        lbl_CompanyIcon.setBounds(190, 210, 129, 44);

        lbl_TradeMarkSymbol.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_TradeMarkSymbol.setText("™");
        panel_Splash.add(lbl_TradeMarkSymbol);
        lbl_TradeMarkSymbol.setBounds(320, 220, 10, 16);

        lbl_CopyrightMention.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_CopyrightMention.setText("Copyright © 2020");
        panel_Splash.add(lbl_CopyrightMention);
        lbl_CopyrightMention.setBounds(10, 230, 120, 20);

        lbl_MiddleImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_MiddleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/Pics/splashscreen.gif"))); // NOI18N
        lbl_MiddleImage.setText("jLabel6");
        panel_Splash.add(lbl_MiddleImage);
        lbl_MiddleImage.setBounds(0, -4, 340, 150);

        lbl_startingImage.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        lbl_startingImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_startingImage.setText("WELCOME");
        panel_Splash.add(lbl_startingImage);
        lbl_startingImage.setBounds(0, 0, 340, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Splash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Splash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_CompanyIcon;
    private javax.swing.JLabel lbl_CopyrightMention;
    private javax.swing.JLabel lbl_EndingImage;
    private javax.swing.JLabel lbl_MiddleImage;
    private javax.swing.JLabel lbl_ProgressMessage;
    private javax.swing.JLabel lbl_TradeMarkSymbol;
    private javax.swing.JLabel lbl_startingImage;
    private javax.swing.JPanel panel_Splash;
    private javax.swing.JProgressBar prgBar_Progress;
    // End of variables declaration//GEN-END:variables
}
